# This is a basic workflow to help you get started with Actions

name: Demo-GH-Action-To-O11y

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ./script.sh

      # Run if it failed
      - name: The job has failed 
        if: ${{ failure() }}
        run: |
          curl -X POST "https://ingest.{REALM}.signalfx.com/v2/event" \
             -H "Content-Type: application/json" \
             -H "X-SF-Token: <value>" \
             -d '[{ "category": "USER_DEFINED", "eventType": "test_event", "dimensions": { "environment": "production", "service": "API" }, "timestamp": 1556793030000 }]'

      # Run if it was successful
      - name: The job has succeeded
        if: ${{ success() }}
        env:
          INGEST_TOKEN: ${{ secrets.INGEST_TOKEN }}
        run: |
          curl -X POST "https://ingest.us1.signalfx.com/v2/event" \
             -H "Content-Type: application/json" \
             -H "X-SF-Token: $env:INGEST_TOKEN" \
             -d '[{ "category": "USER_DEFINED", "eventType": "test_event", "dimensions": { "environment": "production", "service": "API" }, "timestamp": 1687981212 }]'

